steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/fn-prevalence-predictor:latest || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args: [
              'build',
              '-t', 'gcr.io/$PROJECT_ID/fn-prevalence-predictor:latest',
              '--cache-from', 'gcr.io/$PROJECT_ID/fn-prevalence-predictor:latest',
              '.'
          ]
images: ['gcr.io/$PROJECT_ID/fn-prevalence-predictor:latest']