provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor:
    lang: python-geospatial
    handler: ./fn-prevalence-predictor
    image: disarm/fn-prevalence-predictor:0.2.0
    environment:
      exec_timeout: 300
      write_timeout: 310
      read_timeout: 310
      combine_output: false
      # write_debug: true
