provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor:
    lang: dockerfile
    handler: ./fn-prevalence-predictor
    image: disarm/fn-prevalence-predictor:0.1.4
    environment:
      exec_timeout: 120
      write_timeout: 130
      read_timeout: 130
      combine_output: false
      # write_debug: true
