provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor:
    lang: dockerfile
    handler: ./fn-prevalence-predictor
    image: disarm/fn-prevalence-predictor:1.1.5
    environment:
      combine_output: false
