provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor:
    lang: dockerfile
    handler: ./fn-prevalence-predictor
    image: disarm/fn-prevalence-predictor:1.1.6
    environment:
      exec_timeout: 1020
      write_timeout: 1000
      read_timeout: 1000
      combine_output: false
      # write_debug: true
